- name: Install PHP-FPM
  apt:
        pkg={{ item }}
        state=installed
  with_items: php_pkgs
  register: phpfpm_installed

- name: Add Pool Configuration
  when: phpfpm_installed | success
  template:
        src=www.conf.j2
        dest=/etc/php5/fpm/pool.d/www.conf
  notify:
        - Restart FPM
